[features]
seeds = false
skip-lint = false
[programs.devnet]
processing-instruction = "3XgEAxN3vcg3g6rvXRgnT8o61zhcx611MHKjG4yLfJqm"

[registry]
url = "https://anchor.projectserum.com/"

[provider]
cluster = "devnet"
wallet = "/Users/shrihari/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
